login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

register:
    pattern:  /register
    defaults: { _controller: FOSUserBundle:Registration:register }
#    
#check_email:
#    pattern:  /register/check-email
#    defaults: { _controller: DnguUserBundle:Login:checkEmail }
#check_email:
#    pattern:  /register/check-email
#    defaults: { _controller: DnguUserBundle:Login:checkEmail }

