login:
    pattern:  /login
    defaults: { _controller: DnguUserBundle:Login:login }

register:
    pattern:  /register
    defaults: { _controller: DnguUserBundle:Register:register }
    
#register_confirm:
#    pattern:  /register/confirm/{token}
#    defaults: { _controller: DnguUserBundle:Register:register }

check_login:
    pattern:  /logincheck
    defaults: { _controller: DnguUserBundle:Login:check }

weibo_login:
    pattern:  /login/weibo
    defaults: { _controller: DnguUserBundle:Login:weiboLogin }

weibo_callback:
    pattern:  /login/weibo_callback
    defaults: { _controller: DnguUserBundle:Login:weiboCallback }
    
tqq_login:
    pattern:  /login/tqq
    defaults: { _controller: DnguUserBundle:Login:tqqLogin }

tqq_callback:
    pattern:  /login/tqq_callback
    defaults: { _controller: DnguUserBundle:Login:tqqCallback }
    
sns_register:
    pattern:  /register/sns/{oauth}
    defaults: { _controller: DnguUserBundle:Register:sns }
    
register_complete:
    pattern:  /register/complete/{user_id}/{oauth_id}
    defaults: { _controller: DnguUserBundle:Register:complete }
    
    

