login:
    pattern:  /login
    defaults: { _controller: DnguUserBundle:Login:login }

register:
    pattern:  /register
    defaults: { _controller: DnguUserBundle:Register:register }

check_login:
    pattern:  /logincheck
    defaults: { _controller: DnguUserBundle:Login:check }

weibo_login:
    pattern:  /login/weibo
    defaults: { _controller: DnguUserBundle:Login:weiboLogin }

weibo_callback:
    pattern:  /login/weibo_callback
    defaults: { _controller: DnguUserBundle:Login:weiboCallback }

