parameters:
#    dngu_user.example.class: Dngu\UserBundle\Example

services:
    dngu.weibo.oauth:
        class: Dngu\UserBundle\Util\WeiboOauthService
        arguments: [@router, %oauth%]
        
    dngu.tqq.oauth:
        class: Dngu\UserBundle\Util\TqqOauthService
        arguments: [@router, %oauth%]
