<?php

namespace Dngu\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{

    public function getUserAlbumsQuery($user)
    {
        return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->from('DnguWebBundle:Album', 'a')
                        ->where('a.user = :user')
                        ->getQuery()
                        ->setParameter('user', $user);
    }

}
